version: "3"

services:
  webapp:
    build: .
    ports: [ "8081:80" ]
    volumes:
      - ./tasker/:/app/tasker/
      - ./templates/:/app/templates/
      - ./tests/:/app/tests/
      - ./pyproject.toml:/app/pyproject.toml
    command: uvicorn tasker.main:app --host 0.0.0.0 --port 80 --reload
    env_file: [ .env ]
    depends_on:
      - db

  db:
    image: mongo:6.0
#    ports: [ "27017:27017" ]
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: echo 0

volumes:
  mongodata:
