name: tasker
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

base: core22
version: '0.1'
grade: stable
confinement: strict

parts:
  tasker:
    plugin: python
    source: .
    override-build: |
      apt install python3-pip -y
      python3 -m pip install pip --upgrade
      craftctl default
      python3 -m pip install .

apps:
  tasker:
    command: bin/tasker
    environment:
      DATABASE_URI: 'hola'
